<?php

namespace Database\Seeders;

use App\Models\Player;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PlayerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $players = [
            // Goalkeepers
            [
                'first_name' => 'John',
                'last_name' => 'Kayemba',
                'shirt_number' => 1,
                'position' => 'Goalkeeper',
                'date_of_birth' => '1995-03-15',
                'nationality' => 'Uganda',
                'biography' => 'Experienced goalkeeper with excellent shot-stopping ability and commanding presence in the box.',
                'height' => 1.88,
                'weight' => 82.5,
                'preferred_foot' => 'Right',
                'appearances' => 15,
                'goals' => 0,
                'assists' => 2,
                'yellow_cards' => 1,
                'red_cards' => 0,
                'minutes_played' => 1350,
                'joined_date' => '2023-01-15',
            ],
            [
                'first_name' => 'Samuel',
                'last_name' => 'Waiswa',
                'shirt_number' => 30,
                'position' => 'Goalkeeper',
                'date_of_birth' => '1997-07-22',
                'nationality' => 'Uganda',
                'biography' => 'Young and promising goalkeeper with great reflexes and distribution skills.',
                'height' => 1.85,
                'weight' => 78.0,
                'preferred_foot' => 'Left',
                'appearances' => 8,
                'goals' => 0,
                'assists' => 1,
                'yellow_cards' => 0,
                'red_cards' => 0,
                'minutes_played' => 720,
                'joined_date' => '2024-02-01',
            ],

            // Defenders
            [
                'first_name' => 'Moses',
                'last_name' => 'Katumba',
                'shirt_number' => 2,
                'position' => 'Defender',
                'date_of_birth' => '1994-11-08',
                'nationality' => 'Uganda',
                'biography' => 'Solid right-back with pace and crossing ability. A key player in both defense and attack.',
                'height' => 1.78,
                'weight' => 75.5,
                'preferred_foot' => 'Right',
                'appearances' => 18,
                'goals' => 2,
                'assists' => 5,
                'yellow_cards' => 3,
                'red_cards' => 0,
                'minutes_played' => 1620,
                'joined_date' => '2022-06-10',
            ],
            [
                'first_name' => 'Emmanuel',
                'last_name' => 'Ssekajja',
                'shirt_number' => 5,
                'position' => 'Defender',
                'date_of_birth' => '1993-09-12',
                'nationality' => 'Uganda',
                'biography' => 'Central defender and team captain. Strong in the air and excellent leader on the field.',
                'height' => 1.85,
                'weight' => 83.0,
                'preferred_foot' => 'Right',
                'appearances' => 20,
                'goals' => 3,
                'assists' => 2,
                'yellow_cards' => 4,
                'red_cards' => 1,
                'minutes_played' => 1800,
                'joined_date' => '2021-08-15',
            ],
            [
                'first_name' => 'Robert',
                'last_name' => 'Mukiibi',
                'shirt_number' => 4,
                'position' => 'Defender',
                'date_of_birth' => '1996-01-25',
                'nationality' => 'Uganda',
                'biography' => 'Versatile defender who can play center-back or left-back. Good with both feet.',
                'height' => 1.80,
                'weight' => 77.0,
                'preferred_foot' => 'Left',
                'appearances' => 16,
                'goals' => 1,
                'assists' => 3,
                'yellow_cards' => 2,
                'red_cards' => 0,
                'minutes_played' => 1440,
                'joined_date' => '2023-03-20',
            ],

            // Midfielders
            [
                'first_name' => 'David',
                'last_name' => 'Sserwadda',
                'shirt_number' => 8,
                'position' => 'Midfielder',
                'date_of_birth' => '1995-05-18',
                'nationality' => 'Uganda',
                'biography' => 'Creative midfielder with excellent passing range and vision. The playmaker of the team.',
                'height' => 1.75,
                'weight' => 70.5,
                'preferred_foot' => 'Right',
                'appearances' => 19,
                'goals' => 4,
                'assists' => 8,
                'yellow_cards' => 2,
                'red_cards' => 0,
                'minutes_played' => 1710,
                'joined_date' => '2022-01-10',
            ],
            [
                'first_name' => 'Paul',
                'last_name' => 'Kaggwa',
                'shirt_number' => 6,
                'position' => 'Midfielder',
                'date_of_birth' => '1994-12-03',
                'nationality' => 'Uganda',
                'biography' => 'Defensive midfielder with strong tackling and ball-winning abilities.',
                'height' => 1.82,
                'weight' => 79.0,
                'preferred_foot' => 'Right',
                'appearances' => 17,
                'goals' => 1,
                'assists' => 4,
                'yellow_cards' => 6,
                'red_cards' => 0,
                'minutes_played' => 1530,
                'joined_date' => '2023-07-01',
            ],
            [
                'first_name' => 'Isaac',
                'last_name' => 'Muleme',
                'shirt_number' => 10,
                'position' => 'Midfielder',
                'date_of_birth' => '1996-08-14',
                'nationality' => 'Uganda',
                'biography' => 'Attacking midfielder with pace and dribbling skills. Can create chances and score goals.',
                'height' => 1.73,
                'weight' => 68.5,
                'preferred_foot' => 'Left',
                'appearances' => 18,
                'goals' => 6,
                'assists' => 7,
                'yellow_cards' => 3,
                'red_cards' => 0,
                'minutes_played' => 1620,
                'joined_date' => '2022-09-15',
            ],

            // Forwards
            [
                'first_name' => 'Patrick',
                'last_name' => 'Kaddu',
                'shirt_number' => 9,
                'position' => 'Forward',
                'date_of_birth' => '1995-06-20',
                'nationality' => 'Uganda',
                'biography' => 'Clinical striker with great finishing ability. The main goal threat for the team.',
                'height' => 1.83,
                'weight' => 79.5,
                'preferred_foot' => 'Right',
                'appearances' => 20,
                'goals' => 12,
                'assists' => 3,
                'yellow_cards' => 2,
                'red_cards' => 0,
                'minutes_played' => 1800,
                'joined_date' => '2021-12-01',
            ],
            [
                'first_name' => 'Steven',
                'last_name' => 'Mukwala',
                'shirt_number' => 11,
                'position' => 'Forward',
                'date_of_birth' => '1997-04-10',
                'nationality' => 'Uganda',
                'biography' => 'Pacy winger who can play on either flank. Excellent at beating defenders and crossing.',
                'height' => 1.76,
                'weight' => 72.0,
                'preferred_foot' => 'Right',
                'appearances' => 19,
                'goals' => 7,
                'assists' => 9,
                'yellow_cards' => 1,
                'red_cards' => 0,
                'minutes_played' => 1710,
                'joined_date' => '2023-01-20',
            ],
            [
                'first_name' => 'Brian',
                'last_name' => 'Kalumba',
                'shirt_number' => 7,
                'position' => 'Forward',
                'date_of_birth' => '1998-02-28',
                'nationality' => 'Uganda',
                'biography' => 'Young and energetic winger with great potential. Quick and skillful on the ball.',
                'height' => 1.74,
                'weight' => 69.0,
                'preferred_foot' => 'Left',
                'appearances' => 15,
                'goals' => 5,
                'assists' => 4,
                'yellow_cards' => 1,
                'red_cards' => 0,
                'minutes_played' => 1350,
                'joined_date' => '2024-01-15',
            ],
        ];

        foreach ($players as $playerData) {
            Player::create($playerData);
        }
    }
}
